/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSpotifyRouteImport } from './routes/_app.spotify'
import { Route as AppShowcaseRouteImport } from './routes/_app.showcase'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResgatarRouteImport } from './routes/_app.resgatar'
import { Route as AppNicksgunRouteImport } from './routes/_app.nicksgun'
import { Route as AppMissoesRouteImport } from './routes/_app.missoes'
import { Route as AppHubRouteImport } from './routes/_app.hub'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppFarmsRouteImport } from './routes/_app.farms'
import { Route as AppFakeRouteImport } from './routes/_app.fake'
import { Route as AppCloneRouteImport } from './routes/_app.clone'
import { Route as ApiPublicDiscordImageRouteImport } from './routes/api/public/discord-image'
import { Route as ApiPublicAuditRouteImport } from './routes/api/public/audit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSpotifyRoute = AppSpotifyRouteImport.update({
  id: '/spotify',
  path: '/spotify',
  getParentRoute: () => AppRoute,
} as any)
const AppShowcaseRoute = AppShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResgatarRoute = AppResgatarRouteImport.update({
  id: '/resgatar',
  path: '/resgatar',
  getParentRoute: () => AppRoute,
} as any)
const AppNicksgunRoute = AppNicksgunRouteImport.update({
  id: '/nicksgun',
  path: '/nicksgun',
  getParentRoute: () => AppRoute,
} as any)
const AppMissoesRoute = AppMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AppRoute,
} as any)
const AppHubRoute = AppHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmsRoute = AppFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AppRoute,
} as any)
const AppFakeRoute = AppFakeRouteImport.update({
  id: '/fake',
  path: '/fake',
  getParentRoute: () => AppRoute,
} as any)
const AppCloneRoute = AppCloneRouteImport.update({
  id: '/clone',
  path: '/clone',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicDiscordImageRoute = ApiPublicDiscordImageRouteImport.update({
  id: '/api/public/discord-image',
  path: '/api/public/discord-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuditRoute = ApiPublicAuditRouteImport.update({
  id: '/api/public/audit',
  path: '/api/public/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clone': typeof AppCloneRoute
  '/fake': typeof AppFakeRoute
  '/farms': typeof AppFarmsRoute
  '/history': typeof AppHistoryRoute
  '/hub': typeof AppHubRoute
  '/missoes': typeof AppMissoesRoute
  '/nicksgun': typeof AppNicksgunRoute
  '/resgatar': typeof AppResgatarRoute
  '/settings': typeof AppSettingsRoute
  '/showcase': typeof AppShowcaseRoute
  '/spotify': typeof AppSpotifyRoute
  '/api/public/audit': typeof ApiPublicAuditRoute
  '/api/public/discord-image': typeof ApiPublicDiscordImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clone': typeof AppCloneRoute
  '/fake': typeof AppFakeRoute
  '/farms': typeof AppFarmsRoute
  '/history': typeof AppHistoryRoute
  '/hub': typeof AppHubRoute
  '/missoes': typeof AppMissoesRoute
  '/nicksgun': typeof AppNicksgunRoute
  '/resgatar': typeof AppResgatarRoute
  '/settings': typeof AppSettingsRoute
  '/showcase': typeof AppShowcaseRoute
  '/spotify': typeof AppSpotifyRoute
  '/api/public/audit': typeof ApiPublicAuditRoute
  '/api/public/discord-image': typeof ApiPublicDiscordImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/clone': typeof AppCloneRoute
  '/_app/fake': typeof AppFakeRoute
  '/_app/farms': typeof AppFarmsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/hub': typeof AppHubRoute
  '/_app/missoes': typeof AppMissoesRoute
  '/_app/nicksgun': typeof AppNicksgunRoute
  '/_app/resgatar': typeof AppResgatarRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/showcase': typeof AppShowcaseRoute
  '/_app/spotify': typeof AppSpotifyRoute
  '/api/public/audit': typeof ApiPublicAuditRoute
  '/api/public/discord-image': typeof ApiPublicDiscordImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clone'
    | '/fake'
    | '/farms'
    | '/history'
    | '/hub'
    | '/missoes'
    | '/nicksgun'
    | '/resgatar'
    | '/settings'
    | '/showcase'
    | '/spotify'
    | '/api/public/audit'
    | '/api/public/discord-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clone'
    | '/fake'
    | '/farms'
    | '/history'
    | '/hub'
    | '/missoes'
    | '/nicksgun'
    | '/resgatar'
    | '/settings'
    | '/showcase'
    | '/spotify'
    | '/api/public/audit'
    | '/api/public/discord-image'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/clone'
    | '/_app/fake'
    | '/_app/farms'
    | '/_app/history'
    | '/_app/hub'
    | '/_app/missoes'
    | '/_app/nicksgun'
    | '/_app/resgatar'
    | '/_app/settings'
    | '/_app/showcase'
    | '/_app/spotify'
    | '/api/public/audit'
    | '/api/public/discord-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiPublicAuditRoute: typeof ApiPublicAuditRoute
  ApiPublicDiscordImageRoute: typeof ApiPublicDiscordImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/spotify': {
      id: '/_app/spotify'
      path: '/spotify'
      fullPath: '/spotify'
      preLoaderRoute: typeof AppSpotifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/showcase': {
      id: '/_app/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof AppShowcaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resgatar': {
      id: '/_app/resgatar'
      path: '/resgatar'
      fullPath: '/resgatar'
      preLoaderRoute: typeof AppResgatarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nicksgun': {
      id: '/_app/nicksgun'
      path: '/nicksgun'
      fullPath: '/nicksgun'
      preLoaderRoute: typeof AppNicksgunRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/missoes': {
      id: '/_app/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof AppMissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hub': {
      id: '/_app/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AppHubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/farms': {
      id: '/_app/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof AppFarmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fake': {
      id: '/_app/fake'
      path: '/fake'
      fullPath: '/fake'
      preLoaderRoute: typeof AppFakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clone': {
      id: '/_app/clone'
      path: '/clone'
      fullPath: '/clone'
      preLoaderRoute: typeof AppCloneRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/discord-image': {
      id: '/api/public/discord-image'
      path: '/api/public/discord-image'
      fullPath: '/api/public/discord-image'
      preLoaderRoute: typeof ApiPublicDiscordImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit': {
      id: '/api/public/audit'
      path: '/api/public/audit'
      fullPath: '/api/public/audit'
      preLoaderRoute: typeof ApiPublicAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCloneRoute: typeof AppCloneRoute
  AppFakeRoute: typeof AppFakeRoute
  AppFarmsRoute: typeof AppFarmsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppHubRoute: typeof AppHubRoute
  AppMissoesRoute: typeof AppMissoesRoute
  AppNicksgunRoute: typeof AppNicksgunRoute
  AppResgatarRoute: typeof AppResgatarRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShowcaseRoute: typeof AppShowcaseRoute
  AppSpotifyRoute: typeof AppSpotifyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCloneRoute: AppCloneRoute,
  AppFakeRoute: AppFakeRoute,
  AppFarmsRoute: AppFarmsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppHubRoute: AppHubRoute,
  AppMissoesRoute: AppMissoesRoute,
  AppNicksgunRoute: AppNicksgunRoute,
  AppResgatarRoute: AppResgatarRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShowcaseRoute: AppShowcaseRoute,
  AppSpotifyRoute: AppSpotifyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiPublicAuditRoute: ApiPublicAuditRoute,
  ApiPublicDiscordImageRoute: ApiPublicDiscordImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
