
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.site_plans FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.site_features FROM anon;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.spotify_links FROM anon;
REVOKE TRUNCATE, REFERENCES, TRIGGER ON public.site_plans FROM authenticated;
REVOKE TRUNCATE, REFERENCES, TRIGGER ON public.site_features FROM authenticated;
REVOKE TRUNCATE, REFERENCES, TRIGGER ON public.spotify_links FROM authenticated;
